# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Groundwater Transport Phenomena
author: Theodore G. Cleveland, PhD
copyright: "2023"  # Copyright year to be placed in the footer
logo: gwtransport.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
#  execute_notebooks: force
  execute_notebooks: cache
  timeout: -1

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#html:
#  use_issues_button: true
#  use_repository_button: true
html:
  theme:
    name: sphinx_book_theme
    options:
      home_page_in_toc: true       # shows landing page in sidebar
      show_navbar_depth: 1         # similar to RTD expand level
      show_toc_level: 2            # sidebar depth
      use_download_button: true
      use_fullscreen_button: true
      use_issues_button: false
      use_repository_button: false
      use_edit_page_button: false
  extra_css:
    - _static/css/rtd-ish.css   # you can add this later
